In [1]:
# Operation intervals of vehicles
df = pd.read_csv('4_einsaetze_land.csv', sep=';')
df

,land,ort,equipment_nummer,interne_nummer,warenempfaenger,warenempfaenger_nummer,segment,transpondertyp,equi_ok,einsatzbeginn,einsatzende,schichttyp,logout,summe_schocks,kostenstelle,einsatzort,fuehrerscheinklasse,freies_merkmal
0,NaN,NaN,10,10.0,ABC,1,Elektro. Gegengewichtsstapler,Fahrerkarte,1,01.08.2020 00:00:37,01.08.2020 00:29:34,Nicht definiert,Abschaltung,0,NaN,NaN,0,NaN
1,NaN,NaN,653,473.0,ABC,19,Niederhubwagen-KMS,Fahrerkarte,1,01.08.2020 00:05:19,01.08.2020 00:07:57,Nicht definiert,Abschaltung,0,NaN,NaN,0,NaN
2,NaN,NaN,373,306.0,ABC,10,Niederhubwagen,Fahrerkarte,1,01.08.2020 00:06:12,01.08.2020 00:09:10,Nicht definiert,NaN,0,NaN,NaN,0,NaN
3,NaN,NaN,5,5.0,ABC,1,Elektro. Gegengewichtsstapler,Fahrerkarte,1,01.08.2020 00:07:21,01.08.2020 00:44:37,Nicht definiert,Time-Out,0,NaN,NaN,0,NaN
4,NaN,NaN,24,22.0,ABC,1,Elektro. Gegengewichtsstapler,Fahrerkarte,1,01.08.2020 00:14:35,01.08.2020 00:32:20,Nicht definiert,Time-Out,0,NaN,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172255,NaN,NaN,201,NaN,ABC,5,Niederhubwagen,Fahrerkarte,1,31.08.2020 23:55:02,31.08.2020 23:59:34,Vroeg,Spannungsunterbrechung,0,NaN,NaN,0,NaN
172256,NaN,NaN,696,507.0,ABC,20,Schubmaststapler,Fahrerkarte,1,31.08.2020 23:55:40,31.08.2020 23:57:02,Dag,Spannungsunterbrechung,0,NaN,NaN,0,NaN
172257,NaN,NaN,207,158.0,ABC,5,Schubmaststapler,Fahrerkarte,1,31.08.2020 23:55:44,31.08.2020 23:56:33,Vroeg,Spannungsunterbrechung,0,NaN,NaN,0,NaN
172258,NaN,NaN,701,512.0,ABC,20,Schubmaststapler,Fahrerkarte,1,31.08.2020 23:55:51,31.08.2020 23:57:10,Dag,Spannungsunterbrechung,0,NaN,NaN,0,NaN
172259,NaN,NaN,668,488.0,ABC,19,Schubmaststapler,Fahrerkarte,1,31.08.2020 23:56:21,31.08.2020 23:57:24,Nicht definiert,Abschaltung,0,NaN,NaN,0,NaN

In [2]:
columns = ['land','ort','freies_merkmal','fuehrerscheinklasse','einsatzort', 'kostenstelle']
df.drop(columns, inplace=True, axis=1)

In [3]:
df = df.sort_values('equipment_nummer')
df['equipment_nummer'].nunique()

650

In [4]:
df = df.drop_duplicates()

In [5]:
df = df.dropna()

In [6]:
df['einsatzbeginn'] = pd.to_datetime(df['einsatzbeginn'], dayfirst=True)
df['einsatzbeginn'] = pd.to_datetime(df['einsatzbeginn'], format='%d/%m/%y %H:%M:%S')
df['einsatzende'] = pd.to_datetime(df['einsatzende'], dayfirst=True)
df['einsatzende'] = pd.to_datetime(df['einsatzende'], format='%d/%m/%y %H:%M:%S')

In [7]:
df['operated_minutes'] = (df.einsatzende-df.einsatzbeginn) / pd.Timedelta(minutes=1)

In [8]:
df['operated_minutes'] = df['operated_minutes'].round(decimals=2)

In [9]:
df

,equipment_nummer,interne_nummer,warenempfaenger,warenempfaenger_nummer,segment,transpondertyp,equi_ok,einsatzbeginn,einsatzende,schichttyp,logout,summe_schocks,operated_minutes
28079,1,1.0,ABC,1,Elektro. Gegengewichtsstapler,Fahrerkarte,1,2020-08-06 11:49:00,2020-08-06 12:21:20,Nicht definiert,Time-Out,0,32.33
29204,1,1.0,ABC,1,Elektro. Gegengewichtsstapler,Fahrerkarte,1,2020-08-06 13:46:31,2020-08-06 14:58:08,Nicht definiert,Abschaltung,0,71.62
21182,1,1.0,ABC,1,Elektro. Gegengewichtsstapler,Masterkarte,1,2020-08-05 13:28:24,2020-08-05 16:07:38,Nicht definiert,Time-Out,0,159.23
107596,1,1.0,ABC,1,Elektro. Gegengewichtsstapler,Masterkarte,1,2020-08-20 09:15:41,2020-08-20 09:31:30,Nicht definiert,Time-Out,0,15.82
168868,1,1.0,ABC,1,Elektro. Gegengewichtsstapler,Masterkarte,1,2020-08-31 13:31:23,2020-08-31 13:58:03,Nicht definiert,Time-Out,0,26.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68765,920,686.0,ABC,15,Schubmaststapler,Fahrerkarte,1,2020-08-13 12:13:45,2020-08-13 12:29:40,Nicht definiert,Time-Out,0,15.92
10809,920,686.0,ABC,15,Schubmaststapler,Fahrerkarte,1,2020-08-04 09:07:27,2020-08-04 09:14:24,Nicht definiert,Time-Out,0,6.95
69017,920,686.0,ABC,15,Schubmaststapler,Fahrerkarte,1,2020-08-13 12:41:37,2020-08-13 13:07:59,Nicht definiert,Time-Out,0,26.37
50776,920,686.0,ABC,15,Schubmaststapler,Fahrerkarte,1,2020-08-11 09:17:59,2020-08-11 09:22:28,Nicht definiert,Abschaltung,0,4.48
98560,920,686.0,ABC,15,Schubmaststapler,Fahrerkarte,1,2020-08-19 06:58:57,2020-08-19 07:09:52,Nicht definiert,Abschaltung,0,10.92

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 148613 entries, 28079 to 98560
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   equipment_nummer        148613 non-null  int64
 1   interne_nummer          148613 non-null  float64
 2   warenempfaenger         148613 non-null  object
 3   warenempfaenger_nummer  148613 non-null  int64
 4   segment                 148613 non-null  object
 5   transpondertyp          148613 non-null  object
 6   equi_ok                 148613 non-null  int64
 7   einsatzbeginn           148613 non-null  datetime64[ns]
 8   einsatzende             148613 non-null  datetime64[ns]
 9   schichttyp              148613 non-null  object
 10  logout                  148613 non-null  object
 11  summe_schocks           148613 non-null  int64
 12  operated_minutes        148613 non-null  float64
dtypes: datetime64[ns](2), float64(2), int64(4), object(5)
memory usage: 15.9+ MB

In [11]:
df["segment"] = df["segment"].astype('category')
df["transpondertyp"] = df["transpondertyp"].astype('category')
df["schichttyp"] = df["schichttyp"].astype('category')
df["logout"] = df["logout"].astype('category')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 148613 entries, 28079 to 98560
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   equipment_nummer        148613 non-null  int64
 1   interne_nummer          148613 non-null  float64
 2   warenempfaenger         148613 non-null  object
 3   warenempfaenger_nummer  148613 non-null  int64
 4   segment                 148613 non-null  category
 5   transpondertyp          148613 non-null  category
 6   equi_ok                 148613 non-null  int64
 7   einsatzbeginn           148613 non-null  datetime64[ns]
 8   einsatzende             148613 non-null  datetime64[ns]
 9   schichttyp              148613 non-null  category
 10  logout                  148613 non-null  category
 11  summe_schocks           148613 non-null  int64
 12  operated_minutes        148613 non-null  float64
dtypes: category(4), datetime64[ns](2), float64(2), int64(4), object(1)
memory usage: 11.9+ MB

In [13]:
columns = ['einsatzbeginn','einsatzende','warenempfaenger','interne_nummer', 'warenempfaenger_nummer']
df.drop(columns, inplace=True, axis=1)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 148613 entries, 28079 to 98560
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   equipment_nummer  148613 non-null  int64
 1   segment           148613 non-null  category
 2   transpondertyp    148613 non-null  category
 3   equi_ok           148613 non-null  int64
 4   schichttyp        148613 non-null  category
 5   logout            148613 non-null  category
 6   summe_schocks     148613 non-null  int64
 7   operated_minutes  148613 non-null  float64
dtypes: category(4), float64(1), int64(3)
memory usage: 6.2 MB

In [15]:
# Encoding non float or integer variables
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

df_encoded = df.copy()

ord_enc = OrdinalEncoder()
df_encoded["segment"] = ord_enc.fit_transform(df_encoded[["segment"]])
df_encoded["transpondertyp"] = ord_enc.fit_transform(df_encoded[["transpondertyp"]])
df_encoded["schichttyp"] = ord_enc.fit_transform(df_encoded[["schichttyp"]])
df_encoded["logout"] = ord_enc.fit_transform(df_encoded[["logout"]])
df_encoded.head()

,equipment_nummer,segment,transpondertyp,equi_ok,schichttyp,logout,summe_schocks,operated_minutes
28079,1,0.0,0.0,1,5.0,2.0,0,32.33
29204,1,0.0,0.0,1,5.0,0.0,0,71.62
21182,1,0.0,1.0,1,5.0,2.0,0,159.23
107596,1,0.0,1.0,1,5.0,2.0,0,15.82
168868,1,0.0,1.0,1,5.0,2.0,0,26.67

In [16]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 148613 entries, 28079 to 98560
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   equipment_nummer  148613 non-null  int64
 1   segment           148613 non-null  float64
 2   transpondertyp    148613 non-null  float64
 3   equi_ok           148613 non-null  int64
 4   schichttyp        148613 non-null  float64
 5   logout            148613 non-null  float64
 6   summe_schocks     148613 non-null  int64
 7   operated_minutes  148613 non-null  float64
dtypes: float64(5), int64(3)
memory usage: 10.2 MB

In [17]:
df_encoded.corr()

,equipment_nummer,segment,transpondertyp,equi_ok,schichttyp,logout,summe_schocks,operated_minutes
equipment_nummer,1.000000,0.359418,0.053097,-0.019211,0.243380,-0.040004,0.118660,0.087871
segment,0.359418,1.000000,-0.052564,0.040730,-0.040274,-0.102019,0.009537,0.104592
transpondertyp,0.053097,-0.052564,1.000000,-0.005136,0.091971,0.023505,0.025986,-0.019836
equi_ok,-0.019211,0.040730,-0.005136,1.000000,-0.012797,-0.041604,0.018282,0.046681
schichttyp,0.243380,-0.040274,0.091971,-0.012797,1.000000,0.041914,0.010659,-0.030874
logout,-0.040004,-0.102019,0.023505,-0.041604,0.041914,1.000000,-0.004692,0.045787
summe_schocks,0.118660,0.009537,0.025986,0.018282,0.010659,-0.004692,1.000000,0.226120
operated_minutes,0.087871,0.104592,-0.019836,0.046681,-0.030874,0.045787,0.226120,1.000000

In [18]:
corr = df_encoded.corr()
ax = sns.heatmap(
    corr, 
    vmin=-1, vmax=1, center=0,
    cmap=sns.diverging_palette(20, 220, n=200),
    annot_kws={'size':30},
    square=True
)
ax.set_xticklabels(
    ax.get_xticklabels(),
    rotation=45,
    horizontalalignment='right'
);

In [19]:
import math
import matplotlib.pyplot as plt
import numpy as np
from numpy.random import seed
seed(1)
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf

import tensorflow
tensorflow.random.set_seed(1)
from tensorflow.keras import layers
from tensorflow.keras import activations
from tensorflow.keras.layers import Dropout
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.wrappers.scikit_learn import KerasRegressor

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [20]:
training_df = df_encoded.sample(frac=0.7,random_state=200) 
test_df = df_encoded.drop(training_df.index)

In [21]:
operated_minutes = training_df["operated_minutes"]
training_df = training_df.drop('operated_minutes', axis=1)
test_df = test_df.drop('operated_minutes', axis=1)

In [24]:
from sklearn.neural_network import MLPRegressor

modelMLP = MLPRegressor(hidden_layer_sizes=(21), max_iter=1000)
modelMLP.fit(training_df, operated_minutes)

res = modelMLP.predict(test_df)
predicted_df = pd.Series(res)

from sklearn.metrics import r2_score
r_square = modelMLP.score(training_df, operated_minutes)
print("Score Multi-layer Perceptron Regressor: " + str(r_square))

Score Multi-layer Perceptron Regressor: 0.11856780425213742

In [23]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(max_depth=16)
modelRFR = regressor.fit(training_df, operated_minutes)

res = modelRFR.predict(test_df)
predicted_df = pd.Series(res)

from sklearn.metrics import r2_score
r_square = modelRFR.score(training_df, operated_minutes)
print("Score Random Forest Regressor: " + str(r_square))

Score Random Forest Regressor: 0.3954560422905614

In [22]:
from sklearn.tree import DecisionTreeRegressor

regressor = DecisionTreeRegressor(max_depth=16)
modelDTR = regressor.fit(training_df, operated_minutes)

res = modelDTR.predict(test_df)
predicted_df = pd.Series(res)

from sklearn.metrics import r2_score
r_square = modelDTR.score(training_df, operated_minutes)
print("Score Decision Tree Regressor: " + str(r_square))

Score Decision Tree Regressor: 0.38566375454937774

In [ ]:
import warnings
warnings.filterwarnings('ignore')
real_detail_views.to_csv("Real_Detail_views.csv", index=False)
real_detail_views_df = pd.read_csv("Real_Detail_views.csv", header=None)
real_detail_views_df.columns = ['Real_Detail_views_values']
predicted_df.to_csv("prediction_linear_tree_rgr.csv", index=False)
predicted_df_csv = pd.read_csv("prediction_linear_tree_rgr.csv", header=None)
predicted_df_csv.columns = ['Predicted_Detail_views_values']